### PR TITLE
post: creating random positions in 2d

### PR DESCRIPTION
**Pull request by commy2**
As promised.

~~I will add some more content after breakfast.~~
Done.

### CODE REVIEW

**Comment by dedmen** [comment]
Needs a header at the top
Like:
```
---
title: In the Engine - The Scheduler
description: Stuff
author: dedmen
layout: default
category: ITE
---
```
That is just for Jekyll knowing it's thingies. https://jekyllrb.com/docs/frontmatter/
You can also add `language: EN` or DE if you wanna make a german translation someday.

Do you want the pictures to stay on imgur or rather have a local copy on the site?

**Comment by commy2** [comment]
Done.
I could just copy paste the German translation from the AW forums, but honestly, what's the point. The link should be enough.

**Review by dedmen — APPROVED** [review]
Does anyone else want to check language? I don't trust my english enough. 
Could also just merge if no one cares :D

**Comment by commy2** [comment]
Just merge it. I'm already working on the next thing.

**Pull request merged**
